# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='match.proto',
  package='google.cloud.aiplatform.container.v1alpha1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmatch.proto\x12*google.cloud.aiplatform.container.v1alpha1\"\xcb\x01\n\x0cMatchRequest\x12\x19\n\x11\x64\x65ployed_index_id\x18\x01 \x01(\t\x12\x11\n\tfloat_val\x18\x02 \x03(\x02\x12\x15\n\rnum_neighbors\x18\x03 \x01(\x05\x12H\n\trestricts\x18\x04 \x03(\x0b\x32\x35.google.cloud.aiplatform.container.v1alpha1.Namespace\x12,\n$per_crowding_attribute_num_neighbors\x18\x05 \x01(\x05\"\x8f\x01\n\rMatchResponse\x12T\n\x08neighbor\x18\x01 \x03(\x0b\x32\x42.google.cloud.aiplatform.container.v1alpha1.MatchResponse.Neighbor\x1a(\n\x08Neighbor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\"\xa1\x02\n\x11\x42\x61tchMatchRequest\x12i\n\x08requests\x18\x01 \x03(\x0b\x32W.google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest.BatchMatchRequestPerIndex\x1a\xa0\x01\n\x19\x42\x61tchMatchRequestPerIndex\x12\x19\n\x11\x64\x65ployed_index_id\x18\x01 \x01(\t\x12J\n\x08requests\x18\x02 \x03(\x0b\x32\x38.google.cloud.aiplatform.container.v1alpha1.MatchRequest\x12\x1c\n\x14low_level_batch_size\x18\x03 \x01(\x05\"\x8a\x02\n\x12\x42\x61tchMatchResponse\x12l\n\tresponses\x18\x01 \x03(\x0b\x32Y.google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse.BatchMatchResponsePerIndex\x1a\x85\x01\n\x1a\x42\x61tchMatchResponsePerIndex\x12\x19\n\x11\x64\x65ployed_index_id\x18\x01 \x01(\t\x12L\n\tresponses\x18\x02 \x03(\x0b\x32\x39.google.cloud.aiplatform.container.v1alpha1.MatchResponse\"D\n\tNamespace\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x61llow_tokens\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65ny_tokens\x18\x03 \x03(\t2\x9e\x02\n\x0cMatchService\x12~\n\x05Match\x12\x38.google.cloud.aiplatform.container.v1alpha1.MatchRequest\x1a\x39.google.cloud.aiplatform.container.v1alpha1.MatchResponse\"\x00\x12\x8d\x01\n\nBatchMatch\x12=.google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest\x1a>.google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse\"\x00\x62\x06proto3'
)




_MATCHREQUEST = _descriptor.Descriptor(
  name='MatchRequest',
  full_name='google.cloud.aiplatform.container.v1alpha1.MatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deployed_index_id', full_name='google.cloud.aiplatform.container.v1alpha1.MatchRequest.deployed_index_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_val', full_name='google.cloud.aiplatform.container.v1alpha1.MatchRequest.float_val', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_neighbors', full_name='google.cloud.aiplatform.container.v1alpha1.MatchRequest.num_neighbors', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='restricts', full_name='google.cloud.aiplatform.container.v1alpha1.MatchRequest.restricts', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_crowding_attribute_num_neighbors', full_name='google.cloud.aiplatform.container.v1alpha1.MatchRequest.per_crowding_attribute_num_neighbors', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=263,
)


_MATCHRESPONSE_NEIGHBOR = _descriptor.Descriptor(
  name='Neighbor',
  full_name='google.cloud.aiplatform.container.v1alpha1.MatchResponse.Neighbor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='google.cloud.aiplatform.container.v1alpha1.MatchResponse.Neighbor.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='google.cloud.aiplatform.container.v1alpha1.MatchResponse.Neighbor.distance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=409,
)

_MATCHRESPONSE = _descriptor.Descriptor(
  name='MatchResponse',
  full_name='google.cloud.aiplatform.container.v1alpha1.MatchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighbor', full_name='google.cloud.aiplatform.container.v1alpha1.MatchResponse.neighbor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MATCHRESPONSE_NEIGHBOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=409,
)


_BATCHMATCHREQUEST_BATCHMATCHREQUESTPERINDEX = _descriptor.Descriptor(
  name='BatchMatchRequestPerIndex',
  full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest.BatchMatchRequestPerIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deployed_index_id', full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest.BatchMatchRequestPerIndex.deployed_index_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requests', full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest.BatchMatchRequestPerIndex.requests', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low_level_batch_size', full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest.BatchMatchRequestPerIndex.low_level_batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=701,
)

_BATCHMATCHREQUEST = _descriptor.Descriptor(
  name='BatchMatchRequest',
  full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requests', full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest.requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BATCHMATCHREQUEST_BATCHMATCHREQUESTPERINDEX, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=701,
)


_BATCHMATCHRESPONSE_BATCHMATCHRESPONSEPERINDEX = _descriptor.Descriptor(
  name='BatchMatchResponsePerIndex',
  full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse.BatchMatchResponsePerIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deployed_index_id', full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse.BatchMatchResponsePerIndex.deployed_index_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responses', full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse.BatchMatchResponsePerIndex.responses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=837,
  serialized_end=970,
)

_BATCHMATCHRESPONSE = _descriptor.Descriptor(
  name='BatchMatchResponse',
  full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BATCHMATCHRESPONSE_BATCHMATCHRESPONSEPERINDEX, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=704,
  serialized_end=970,
)


_NAMESPACE = _descriptor.Descriptor(
  name='Namespace',
  full_name='google.cloud.aiplatform.container.v1alpha1.Namespace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.aiplatform.container.v1alpha1.Namespace.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allow_tokens', full_name='google.cloud.aiplatform.container.v1alpha1.Namespace.allow_tokens', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deny_tokens', full_name='google.cloud.aiplatform.container.v1alpha1.Namespace.deny_tokens', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=972,
  serialized_end=1040,
)

_MATCHREQUEST.fields_by_name['restricts'].message_type = _NAMESPACE
_MATCHRESPONSE_NEIGHBOR.containing_type = _MATCHRESPONSE
_MATCHRESPONSE.fields_by_name['neighbor'].message_type = _MATCHRESPONSE_NEIGHBOR
_BATCHMATCHREQUEST_BATCHMATCHREQUESTPERINDEX.fields_by_name['requests'].message_type = _MATCHREQUEST
_BATCHMATCHREQUEST_BATCHMATCHREQUESTPERINDEX.containing_type = _BATCHMATCHREQUEST
_BATCHMATCHREQUEST.fields_by_name['requests'].message_type = _BATCHMATCHREQUEST_BATCHMATCHREQUESTPERINDEX
_BATCHMATCHRESPONSE_BATCHMATCHRESPONSEPERINDEX.fields_by_name['responses'].message_type = _MATCHRESPONSE
_BATCHMATCHRESPONSE_BATCHMATCHRESPONSEPERINDEX.containing_type = _BATCHMATCHRESPONSE
_BATCHMATCHRESPONSE.fields_by_name['responses'].message_type = _BATCHMATCHRESPONSE_BATCHMATCHRESPONSEPERINDEX
DESCRIPTOR.message_types_by_name['MatchRequest'] = _MATCHREQUEST
DESCRIPTOR.message_types_by_name['MatchResponse'] = _MATCHRESPONSE
DESCRIPTOR.message_types_by_name['BatchMatchRequest'] = _BATCHMATCHREQUEST
DESCRIPTOR.message_types_by_name['BatchMatchResponse'] = _BATCHMATCHRESPONSE
DESCRIPTOR.message_types_by_name['Namespace'] = _NAMESPACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatchRequest = _reflection.GeneratedProtocolMessageType('MatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _MATCHREQUEST,
  '__module__' : 'match_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.aiplatform.container.v1alpha1.MatchRequest)
  })
_sym_db.RegisterMessage(MatchRequest)

MatchResponse = _reflection.GeneratedProtocolMessageType('MatchResponse', (_message.Message,), {

  'Neighbor' : _reflection.GeneratedProtocolMessageType('Neighbor', (_message.Message,), {
    'DESCRIPTOR' : _MATCHRESPONSE_NEIGHBOR,
    '__module__' : 'match_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.aiplatform.container.v1alpha1.MatchResponse.Neighbor)
    })
  ,
  'DESCRIPTOR' : _MATCHRESPONSE,
  '__module__' : 'match_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.aiplatform.container.v1alpha1.MatchResponse)
  })
_sym_db.RegisterMessage(MatchResponse)
_sym_db.RegisterMessage(MatchResponse.Neighbor)

BatchMatchRequest = _reflection.GeneratedProtocolMessageType('BatchMatchRequest', (_message.Message,), {

  'BatchMatchRequestPerIndex' : _reflection.GeneratedProtocolMessageType('BatchMatchRequestPerIndex', (_message.Message,), {
    'DESCRIPTOR' : _BATCHMATCHREQUEST_BATCHMATCHREQUESTPERINDEX,
    '__module__' : 'match_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest.BatchMatchRequestPerIndex)
    })
  ,
  'DESCRIPTOR' : _BATCHMATCHREQUEST,
  '__module__' : 'match_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.aiplatform.container.v1alpha1.BatchMatchRequest)
  })
_sym_db.RegisterMessage(BatchMatchRequest)
_sym_db.RegisterMessage(BatchMatchRequest.BatchMatchRequestPerIndex)

BatchMatchResponse = _reflection.GeneratedProtocolMessageType('BatchMatchResponse', (_message.Message,), {

  'BatchMatchResponsePerIndex' : _reflection.GeneratedProtocolMessageType('BatchMatchResponsePerIndex', (_message.Message,), {
    'DESCRIPTOR' : _BATCHMATCHRESPONSE_BATCHMATCHRESPONSEPERINDEX,
    '__module__' : 'match_pb2'
    # @@protoc_insertion_point(class_scope:google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse.BatchMatchResponsePerIndex)
    })
  ,
  'DESCRIPTOR' : _BATCHMATCHRESPONSE,
  '__module__' : 'match_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.aiplatform.container.v1alpha1.BatchMatchResponse)
  })
_sym_db.RegisterMessage(BatchMatchResponse)
_sym_db.RegisterMessage(BatchMatchResponse.BatchMatchResponsePerIndex)

Namespace = _reflection.GeneratedProtocolMessageType('Namespace', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACE,
  '__module__' : 'match_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.aiplatform.container.v1alpha1.Namespace)
  })
_sym_db.RegisterMessage(Namespace)



_MATCHSERVICE = _descriptor.ServiceDescriptor(
  name='MatchService',
  full_name='google.cloud.aiplatform.container.v1alpha1.MatchService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1043,
  serialized_end=1329,
  methods=[
  _descriptor.MethodDescriptor(
    name='Match',
    full_name='google.cloud.aiplatform.container.v1alpha1.MatchService.Match',
    index=0,
    containing_service=None,
    input_type=_MATCHREQUEST,
    output_type=_MATCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BatchMatch',
    full_name='google.cloud.aiplatform.container.v1alpha1.MatchService.BatchMatch',
    index=1,
    containing_service=None,
    input_type=_BATCHMATCHREQUEST,
    output_type=_BATCHMATCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATCHSERVICE)

DESCRIPTOR.services_by_name['MatchService'] = _MATCHSERVICE

# @@protoc_insertion_point(module_scope)
